#spring:
#  profiles:
#    active: dev
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: dev
#
#server:
#  address: 0.0.0.0
#  port: 8081
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: uat
#
#server:
#  address: 127.100.100.100
#  port: 8181
