spring:
  theinvestorthing:
    author: Alessandro De Vincenti
    version: 0.1.1
    module: backend
    name: the-investorthing-be
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: uat

server:
  port: 8181


---

spring:
  activate:
    on-profile: prod

server:
  port: 8080



